// Liste der verfügbaren Übungen
const exercises = [
    { name: "Jumping Jacks", duration: 30, difficulty: 1, switchSides: false },
    { name: "Jumping Jacks", duration: 60, difficulty: 2, switchSides: false },
    { name: "Jumping Jacks", duration: 90, difficulty: 3, switchSides: false },
    { name: "Plank", duration: 45, difficulty: 2, switchSides: false },
    { name: "Plank", duration: 60, difficulty: 3, switchSides: false },
    { name: "Plank", duration: 90, difficulty: 4, switchSides: false },
    { name: "Plank", duration: 105, difficulty: 5, switchSides: false },
    { name: "Squads", duration: 30, difficulty: 1, switchSides: false },
    { name: "Squads", duration: 45, difficulty: 2, switchSides: false },
    { name: "Squads", duration: 60, difficulty: 3, switchSides: false },
    { name: "Ausfallschritte", duration: 60, difficulty: 1, switchSides: false },
    { name: "Ausfallschritte", duration: 90, difficulty: 2, switchSides: false },
    { name: "Ausfallschritte", duration: 120, difficulty: 3, switchSides: false },
    { name: "Bergsteiger - gerade", duration: 45, difficulty: 1, switchSides: false },
    { name: "Bergsteiger - gerade", duration: 60, difficulty: 2, switchSides: false },
    { name: "Bergsteiger - gerade", duration: 75, difficulty: 3, switchSides: false },
    { name: "Bergsteiger - gerade", duration: 90, difficulty: 4, switchSides: false },
    { name: "Bergsteiger - diagonal", duration: 45, difficulty: 1, switchSides: false },
    { name: "Bergsteiger - diagonal", duration: 60, difficulty: 2, switchSides: false },
    { name: "Bergsteiger - diagonal", duration: 75, difficulty: 3, switchSides: false },
    { name: "Bergsteiger - diagonal", duration: 90, difficulty: 4, switchSides: false },
    { name: "Sit-Ups", duration: 30, difficulty: 1, switchSides: false },
    { name: "Sit-Ups", duration: 45, difficulty: 2, switchSides: false },
    { name: "Sit-Ups", duration: 60, difficulty: 3, switchSides: false },
    { name: "Sit-Ups", duration: 90, difficulty: 4, switchSides: false },
    { name: "Sit-Ups", duration: 120, difficulty: 5, switchSides: false },
    { name: "Liegestütze", duration: 30, difficulty: 1, switchSides: false },
    { name: "Liegestütze", duration: 45, difficulty: 2, switchSides: false },
    { name: "Liegestütze", duration: 60, difficulty: 3, switchSides: false },
    { name: "Liegestütze", duration: 90, difficulty: 4, switchSides: false },
    { name: "Liegestütze", duration: 120, difficulty: 5, switchSides: false },
    { name: "Seitstütz", duration: 45, difficulty: 2, switchSides: true },
    { name: "Seitstütz", duration: 60, difficulty: 3, switchSides: true },
    { name: "Seitstütz", duration: 90, difficulty: 4, switchSides: true },
    { name: "Seitstütz", duration: 105, difficulty: 5, switchSides: true },
    { name: "Hock-Streck-Sprünge", duration: 30, difficulty: 1, switchSides: false },
    { name: "Hock-Streck-Sprünge", duration: 45, difficulty: 2, switchSides: false },
    { name: "Hock-Streck-Sprünge", duration: 60, difficulty: 3, switchSides: false },
    { name: "Hock-Streck-Sprünge", duration: 105, difficulty: 4, switchSides: false },
    { name: "Arm-/ Beinheben", duration: 30, difficulty: 1, switchSides: false },
    { name: "Arm-/ Beinheben", duration: 60, difficulty: 2, switchSides: false },
    { name: "Arm-/ Beinheben", duration: 75, difficulty: 3, switchSides: false },
    { name: "Arm-/ Beinheben", duration: 90, difficulty: 4, switchSides: false },
    { name: "Beckenheben", duration: 30, difficulty: 1, switchSides: false },
    { name: "Beckenheben", duration: 60, difficulty: 2, switchSides: false },
    { name: "Beckenheben", duration: 75, difficulty: 3, switchSides: false },
    { name: "Beckenheben", duration: 105, difficulty: 4, switchSides: false },
    { name: "Beckenheben", duration: 120, difficulty: 5, switchSides: false },
];